apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authservice
    template:
        metadata:
            labels:
                app: authservice
        spec:
            containers:
                - name: authservice
                  image: rdani2005/authservice:latest
---
apiVersion: v1
kind: Service
metadata:
    name: auth-clousterip-srv
spec:
    type: ClusterIP
    selector:
        app: authservice
    ports:
        - name: authservice
          protocol: TCP
          port: 80
          targetPort: 80
        - name: authgrpc
          protocol: TCP
          port: 666
          targetPort: 666
